-- AlterTable
ALTER TABLE `Ordini` MODIFY `Indirizzo` VARCHAR(256) NOT NULL,
    MODIFY `Cap` VARCHAR(256) NOT NULL;

-- AlterTable
ALTER TABLE `Utente` MODIFY `CF` VARCHAR(256) NOT NULL,
    MODIFY `Nascita` VARCHAR(256) NOT NULL,
    MODIFY `Telefono` VARCHAR(256) NOT NULL;
