name: Upload new site
on: [push]
jobs:
  build:
    name: Building website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building Website 
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - run: npm i
      - run: mv src/lib/crypto/config.example src/lib/crypto/config.json
      - run: npm run build
  upload:
    name: Connect to VPS
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: bash Website-Nex/update.sh
